### PR TITLE
Vet Clinic DB: database performance audit

### PR DESCRIPTION
**Pull request by ibr5500**
### In this [PR] we (@GOlivierNation, @ibr5500) have:

> - ADD COLUMN email for the owners table & insert data to it.
> - Insert data to the visits table.
> - Use explains analysis to get the execution time.
> - Use Index-Only Scans to improve, and decrease to execution time.
> - Update README file.

#### EXPLAIN ANALYZE for the visits table (animals_id).
p4-screen1
p4-screen5

#### EXPLAIN ANALYZE for the visits table (vet_id).
p4-screen2
p4-screen4

#### EXPLAIN ANALYZE for the owners table.
p4-screen3
p4-screen6

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @ibr5500 @GOlivierNation, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional Readme
✔️ Correct Gitflow

## Required 
- [x] Kindly make sure to add the screenshots in the pull request as per the requirement. I can see that you have added the screenshots to the readme. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ibr5500** [comment]
Thank you @sja-thedude for the code review

**Review by keroloussamy — APPROVED** [review]
Hi @ibr5500, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯


- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ibr5500** [comment]
Thank you @keroloussamy  for the code review.

**Pull request merged**
